POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Vladyslav Completes Fullstackopen Course",
  "author": "V. Ostapchuk",
  "url": "https://github.com/ostapvladyslav/Fullstackopen",
  "likes": 5,
  "userId": "63fa67016876102e5e309d30"
}
